In [2]:
!pip install nashpy


In [3]:
import numpy as np
import nashpy as nash

# Definir matriz de pagos
# Empresa A: filas, Empresa B: columnas
# Formato: (pago_A, pago_B)
payoff_A = np.array([
    [3, 5],
    [1, 4]
])

payoff_B = np.array([
    [3, 1],
    [5, 4]
])

# Crear juego
game = nash.Game(payoff_A, payoff_B)

# Mostrar juego
print("Juego definido:")
print(game)

# Calcular equilibrios de Nash
equilibria = list(game.support_enumeration())
print("\nEquilibrios de Nash encontrados:")
for eq in equilibria:
    print(f"Estrategia Empresa A: {eq[0]}, Estrategia Empresa B: {eq[1]}")


Juego definido:
Bi matrix game with payoff matrices:

Row player:
[[3 5]
 [1 4]]

Column player:
[[3 1]
 [5 4]]

Equilibrios de Nash encontrados:
Estrategia Empresa A: [1. 0.], Estrategia Empresa B: [1. 0.]


In [4]:
import numpy as np
import nashpy as nash

# Matriz de pagos avanzada con 3 estrategias
payoff_A = np.array([
    [2, 4, 5],
    [1, 3, 4],
    [0, 2, 3]
])

payoff_B = np.array([
    [2, 1, 0],
    [4, 3, 2],
    [5, 4, 3]
])

game_adv = nash.Game(payoff_A, payoff_B)

print("Juego avanzado definido (3 estrategias):")
print(game_adv)

# Equilibrios de Nash (pueden ser mixtos)
equilibria = list(game_adv.support_enumeration())
print("\nEquilibrios de Nash encontrados:")
for eq in equilibria:
    strat_A, strat_B = eq
    print(f"Estrategia Empresa A: {np.round(strat_A, 2)}")
    print(f"Estrategia Empresa B: {np.round(strat_B, 2)}")


Juego avanzado definido (3 estrategias):
Bi matrix game with payoff matrices:

Row player:
[[2 4 5]
 [1 3 4]
 [0 2 3]]

Column player:
[[2 1 0]
 [4 3 2]
 [5 4 3]]

Equilibrios de Nash encontrados:
Estrategia Empresa A: [1. 0. 0.]
Estrategia Empresa B: [1. 0. 0.]


In [5]:
payoff_A_mix = np.array([
    [1, -1],
    [-1, 1]
])

payoff_B_mix = np.array([
    [1, -1],
    [-1, 1]
])

game_mix = nash.Game(payoff_A_mix, payoff_B_mix)
print("Juego mixto puro (clásico Matching Pennies):")
print(game_mix)

equilibria_mix = list(game_mix.support_enumeration())
print("\nEquilibrio mixto (Matching Pennies):")
for eq in equilibria_mix:
    print(f"Estrategia Empresa A: {np.round(eq[0], 2)}, Estrategia Empresa B: {np.round(eq[1], 2)}")


Juego mixto puro (clásico Matching Pennies):
Bi matrix game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[ 1 -1]
 [-1  1]]

Equilibrio mixto (Matching Pennies):
Estrategia Empresa A: [1. 0.], Estrategia Empresa B: [1. 0.]
Estrategia Empresa A: [0. 1.], Estrategia Empresa B: [0. 1.]
Estrategia Empresa A: [0.5 0.5], Estrategia Empresa B: [0.5 0.5]


In [6]:
payoff_A_asym = np.array([
    [3, 4, 5],
    [2, 3, 4],
    [1, 2, 3]
])

payoff_B_asym = np.array([
    [2, 1, 0],
    [3, 3, 2],
    [4, 4, 3]
])

game_asym = nash.Game(payoff_A_asym, payoff_B_asym)
print("\nJuego asimétrico realista definido:")
print(game_asym)

equilibria_asym = list(game_asym.support_enumeration())
print("\nEquilibrios de Nash en juego asimétrico:")
for eq in equilibria_asym:
    print(f"Estrategia Empresa A: {np.round(eq[0], 2)}, Estrategia Empresa B: {np.round(eq[1], 2)}")



Juego asimétrico realista definido:
Bi matrix game with payoff matrices:

Row player:
[[3 4 5]
 [2 3 4]
 [1 2 3]]

Column player:
[[2 1 0]
 [3 3 2]
 [4 4 3]]

Equilibrios de Nash en juego asimétrico:
Estrategia Empresa A: [1. 0. 0.], Estrategia Empresa B: [1. 0. 0.]


In [7]:
sigma_A = np.array([0.5, 0.5])  # equilibrio mixto en Matching Pennies
sigma_B = np.array([0.5, 0.5])

expected_payoff_A = sigma_A @ payoff_A_mix @ sigma_B.T
expected_payoff_B = sigma_A @ payoff_B_mix @ sigma_B.T

print("\nPagos esperados bajo equilibrio mixto (Matching Pennies):")
print(f"Pago esperado Empresa A: {expected_payoff_A:.2f}")
print(f"Pago esperado Empresa B: {expected_payoff_B:.2f}")



Pagos esperados bajo equilibrio mixto (Matching Pennies):
Pago esperado Empresa A: 0.00
Pago esperado Empresa B: 0.00
